File argsFile = new File(basedir, "lychee-args.txt")
assert argsFile.isFile()
String out = argsFile.getText("UTF-8")
assert out.contains("--no-progress")
assert out.contains("--verbose")
assert out.contains("--format")
assert out.contains("compact")
assert out.contains("--mode")
assert out.contains("plain")
assert out.contains("--files-from")

File inputsFile = new File(basedir, "lychee-inputs.txt")
assert inputsFile.isFile()
String inputs = inputsFile.getText("UTF-8")
assert inputs.contains("docs/good.md")
assert inputs.contains("guide/index.adoc")
assert !inputs.contains("docs/skip.md")
return true
