name: CI

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  build:
    if: github.event_name != 'pull_request_target' || github.actor == 'github-actions[bot]' || github.actor == 'release-please[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}

      - name: Set up Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build, unit+integration tests, package
        run: ./mvnw -B verify

      - name: Generate site
        run: ./mvnw -B site

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom-17
          path: |
            target/bom.xml
            target/bom.json
